"""Audit report generation (PRD R13, TR-12).

Renders a structured, document-like PDF from persisted case + project +
signal + evidence data via ReportLab. The report preserves the distinction
between automated signals, evidence, peer context and officer conclusions —
automated output is never written as an official finding.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.errors import NotFoundError
from app.models import (
    CaseEvent,
    CaseEvidence,
    CaseNote,
    InvestigationCase,
    Officer,
    Project,
    ProjectPeer,
    Report,
)
from app.services.cases.cases import next_case_report_number

logger = logging.getLogger("drishti.reports")


def _rs(t: str) -> str:
    """Escape XML entities for ReportLab Paragraphs."""
    return (
        t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    )


def generate_case_report(db: Session, case: InvestigationCase, officer: Officer) -> Report:
    """Generate and persist the PDF report for a case."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        HRFlowable,
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    project: Project = case.project
    signals = sorted(
        project.signals,
        key=lambda s: ({"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}.get(s.severity, 9), s.signal_type),
    )

    storage = Path(settings.report_storage_path)
    storage.mkdir(parents=True, exist_ok=True)
    report_number = next_case_report_number(db, case)
    file_path = storage / f"{report_number}.pdf"

    doc = SimpleDocTemplate(
        str(file_path),
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        title=f"TRINETRA Investigation Report {report_number}",
    )

    styles = getSampleStyleSheet()
    base = ParagraphStyle("base", parent=styles["Normal"], fontName="Helvetica", fontSize=9, leading=12.5)
    h1 = ParagraphStyle("h1", parent=base, fontName="Helvetica-Bold", fontSize=15, leading=18, spaceAfter=2)
    h2 = ParagraphStyle("h2", parent=base, fontName="Helvetica-Bold", fontSize=10.5, leading=14,
                        spaceBefore=10, spaceAfter=4, textColor=colors.HexColor("#1f2937"))
    small = ParagraphStyle("small", parent=base, fontSize=7.5, leading=10, textColor=colors.HexColor("#4b5563"))
    cell = ParagraphStyle("cell", parent=base, fontSize=8, leading=10.5)
    cell_bold = ParagraphStyle("cellb", parent=cell, fontName="Helvetica-Bold")

    story: list = []
    generated_at = datetime.now(timezone.utc)

    # --- Header -----------------------------------------------------------
    story.append(Paragraph("TRINETRA — INVESTIGATION SUPPORT REPORT", h1))
    story.append(Paragraph(
        "Decision-support document. Signals below are automated indicators, "
        "not official findings. Verification and classification are performed by officers.",
        small,
    ))
    story.append(HRFlowable(width="100%", thickness=0.8, color=colors.HexColor("#111827"),
                            spaceBefore=6, spaceAfter=10))

    meta = [
        ["Report number", report_number, "Generated at", generated_at.strftime("%Y-%m-%d %H:%M UTC")],
        ["Case", case.case_number, "Case status", case.status],
        ["Work ID", project.work_id, "Priority", case.priority],
        ["District", f"{project.district}, {project.state}", "Generated by", officer.name],
        ["Dataset version", project.dataset.version if project.dataset else "—",
         "Provenance", "SYNTHETIC DEMO DATA" if (project.dataset and project.dataset.is_synthetic) else "Official import"],
    ]
    meta_table = Table([[Paragraph(_rs(str(c)), cell if i % 2 == 0 else cell_bold) for i, c in enumerate(row)]
                        for row in meta], colWidths=[28 * mm, 55 * mm, 26 * mm, 58 * mm])
    meta_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d1d5db")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f3f4f6")),
        ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#f3f4f6")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(meta_table)

    # --- Project information ----------------------------------------------
    story.append(Paragraph("1. Project information", h2))
    story.append(Paragraph(_rs(project.description), base))
    fin = f"{float(project.financial_progress):.0f}%" if project.financial_progress is not None else "—"
    phy = f"{float(project.physical_progress):.0f}%" if project.physical_progress is not None else "—"
    story.append(Paragraph(
        f"Status: {_rs(project.status)} · Category: {_rs(project.category or '—')} · "
        f"Financial progress: {fin} · Physical progress: {phy} · "
        f"Sanctioned: ₹{float(project.sanctioned_cost):,.0f} · "
        f"Expenditure: {'₹' + format(float(project.expenditure), ',.0f') if project.expenditure is not None else '—'}",
        base,
    ))

    # --- Signals + evidence ledger -----------------------------------------
    story.append(Paragraph("2. Detected signals and evidence", h2))
    if not signals:
        story.append(Paragraph("No signals recorded for this project.", base))
    for s in signals:
        story.append(Paragraph(f"{_rs(s.title)}  <font size=7.5 color=#6b7280>[{s.signal_type} · {s.severity} · {s.source_type}]</font>", cell_bold))
        story.append(Paragraph(_rs(s.explanation), cell))
        ev_rows = [[Paragraph("<b>Observed</b>", cell), Paragraph("<b>Reference</b>", cell), Paragraph("<b>Calculation</b>", cell)]]
        for e in s.evidence:
            ev_rows.append([
                Paragraph(f"{_rs(e.field_name)}: {_rs(e.field_value or '')}", cell),
                Paragraph(f"{_rs(e.reference_label or '')} {_rs(e.reference_value or '')}", cell),
                Paragraph(_rs(e.calculation or ""), cell),
            ])
        if len(ev_rows) > 1:
            t = Table(ev_rows, colWidths=[52 * mm, 58 * mm, 58 * mm])
            t.setStyle(TableStyle([
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#e5e7eb")),
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f9fafb")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ]))
            story.append(t)
        story.append(Spacer(1, 6))

    # --- Peer context --------------------------------------------------------
    story.append(Paragraph("3. Peer context", h2))
    peers = db.query(ProjectPeer).filter(ProjectPeer.project_id == project.id).all()
    if not peers:
        story.append(Paragraph("Insufficient comparable projects for a peer benchmark.", base))
    for pp in peers:
        story.append(Paragraph(
            f"Peer group “{_rs(pp.peer_group.name)}” — {pp.peer_count} comparable works · "
            f"median ₹{float(pp.median_cost):,.0f} · P75 ₹{float(pp.p75_cost):,.0f} · "
            f"this work at percentile {float(pp.percentile):.0f}.",
            base,
        ))

    # --- Timeline -------------------------------------------------------------
    story.append(Paragraph("4. Timeline", h2))
    tl = [
        ("Sanctioned", project.sanction_date),
        ("Started", project.start_date),
        ("Expected completion", None),
        ("Recorded completion", project.completion_date),
    ]
    for label, d in tl:
        if label == "Expected completion" and project.expected_duration_days and project.sanction_date:
            from datetime import timedelta
            d = project.sanction_date + timedelta(days=project.expected_duration_days)
        if d:
            story.append(Paragraph(f"• {label}: {d.isoformat()}", base))

    # --- Case record -----------------------------------------------------------
    story.append(Paragraph("5. Case record and officer remarks", h2))
    if case.status == "CLOSED":
        # A cleared case still shows its original automated flags (section 2
        # is untouched) plus the explicit human outcome and its reasoning —
        # clearing a flag never erases the detection history.
        story.append(Paragraph(
            "<b>Investigation outcome: NOT SUBSTANTIATED.</b> Human "
            "investigation did not substantiate the flagged concern. This is "
            "not a finding of fraud or of innocence, and it does not imply the "
            "automated signals were wrong: the available evidence did not "
            "substantiate the concern. The original AI-generated signals are "
            "preserved above as historical detection evidence.",
            base,
        ))
        reason_label = {
            "DOCUMENTATION_PROVIDED": "Documentation provided",
            "LEGITIMATE_DELAY": "Legitimate implementation delay",
            "DATA_QUALITY_ISSUE": "Data quality issue",
            "FALSE_DUPLICATE_CANDIDATE": "False duplicate candidate",
            "APPROVED_VARIATION": "Approved variation",
            "CONTEXTUAL_EXCEPTION": "Contextual exception",
            "OTHER": "Other",
        }.get(case.resolution_reason or "", case.resolution_reason or "—")
        story.append(Paragraph(
            f"Outcome classification: {case.resolution_type or '—'} · "
            f"Reason category: {_rs(reason_label)}",
            cell,
        ))
        story.append(Spacer(1, 2))
    for ev in case.events:
        when = ev.created_at.strftime("%Y-%m-%d %H:%M") if ev.created_at else ""
        desc = f"{ev.event_type}"
        if ev.from_status or ev.to_status:
            desc += f" ({ev.from_status or '—'} → {ev.to_status or '—'})"
        story.append(Paragraph(f"• {when} — {_rs(desc)}", small))
    story.append(Spacer(1, 4))
    notes = db.query(CaseNote).filter(CaseNote.case_id == case.id).order_by(CaseNote.created_at).all()
    if notes:
        for n in notes:
            who = n.author.name if n.author else "Officer"
            story.append(Paragraph(f"Note by {_rs(who)}: {_rs(n.body)}", base))
    else:
        story.append(Paragraph("No officer notes recorded.", base))
    att = db.query(CaseEvidence).filter(CaseEvidence.case_id == case.id).all()
    if att:
        story.append(Paragraph("Attached evidence references:", cell_bold))
        for a in att:
            story.append(Paragraph(f"• {_rs(a.description)} [{_rs(a.evidence_type)}]", small))

    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#9ca3af")))

    # --- Evidence hash manifest (backlog #2: chain of custody) ---------------
    # sha256 over every persisted record included in this report — signals,
    # evidence rows, case events, notes. Deterministic, independently
    # recomputable, and cited in the footer so a recipient can verify the
    # included content has not changed since generation.
    import hashlib
    import json as _json

    def _h(obj) -> str:
        return hashlib.sha256(
            _json.dumps(obj, sort_keys=True, default=str, ensure_ascii=False).encode("utf-8")
        ).hexdigest()

    manifest_items: list[dict] = [
        {"kind": "signal", "id": s.id, "hash": _h({
            "id": s.id, "type": s.signal_type, "severity": s.severity,
            "title": s.title, "explanation": s.explanation,
            "observed": s.observed_value, "reference": s.reference_value,
            "difference": s.difference_value, "created": str(s.created_at)})}
        for s in signals
    ]
    for s in signals:
        for e in s.evidence:
            manifest_items.append({"kind": "evidence", "id": e.id, "hash": _h({
                "id": e.id, "field": e.field_name, "value": e.field_value,
                "reference": e.reference_value, "calculation": e.calculation})})
    for ev in case.events:
        manifest_items.append({"kind": "case_event", "id": ev.id, "hash": _h({
            "id": ev.id, "type": ev.event_type, "from": ev.from_status,
            "to": ev.to_status, "created": str(ev.created_at)})})
    for n in notes:
        manifest_items.append({"kind": "note", "id": n.id, "hash": _h({
            "id": n.id, "author": n.author_id, "body": n.body,
            "created": str(n.created_at)})})
    manifest_hash = _h(manifest_items)

    story.append(Paragraph("6. Evidence integrity manifest", h2))
    story.append(Paragraph(
        f"This report covers {len(manifest_items)} persisted records (signals, "
        "evidence rows, case events, officer notes). Each record's SHA-256 hash "
        "is included in the platform's manifest for this report; the manifest "
        "root is printed below so any later alteration of the included content "
        "is detectable.", base,
    ))
    story.append(Paragraph(
        f"<font name='Courier' size=7.5>manifest-root: {manifest_hash}</font>", cell,
    ))
    story.append(Paragraph(
        "Platform audit chain (all case actions, hash-linked) can be verified at "
        "GET /api/v1/audit/verify.", small,
    ))

    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#9ca3af")))
    story.append(Paragraph(
        f"Report {report_number} · version {case.id[:8]} · generated {generated_at.isoformat()} · "
        f"model {settings.model_version} · ruleset {settings.ruleset_version} · "
        f"manifest {manifest_hash[:16]}… . "
        f"This report supports investigation; it does not constitute an official finding.",
        small,
    ))

    doc.build(story)

    report = Report(
        case_id=case.id,
        report_number=report_number,
        format="PDF",
        file_reference=str(file_path),
        generated_by=officer.id,
        report_version="v1",
    )
    db.add(report)
    db.add(CaseEvent(
        case_id=case.id,
        event_type="REPORT_GENERATED",
        actor_id=officer.id,
        metadata_json={"report_number": report_number},
    ))
    db.commit()
    db.refresh(report)
    return report
